interest:
  business-rate: 1.5       # percent
  business-cap: 10000.0    # max daily gain per business
  player-rate: 0.1         # percent player rate

withdraw:
  daily-limit: 5000.0      # max per player per day
  enabled: true

bank-notes:
  enabled: true

tax:
  enabled: true            # whether the tax system is active
  rate: 0.1                # 10% tax on earnings (as a decimal)
  recipient: "00000000-0000-0000-0000-000000000001"  # UUID of the government/server account DO NOT CHANGE
  apply-on-interest: true  # apply tax on daily interest earnings
  apply-on-transfers: false # apply tax on player-to-player or business transfers